### ISSUE TITLE
How to link to each individual contributor with the "contributors" badge

### ISSUE THREAD

**Issue by stefanobartoletti** [pujux/badge-it#29]
At the moment, when using the "contributors" badge, by default the whole widget including all contributors pictures is linked to an external `<svg>` that contains links to each individual contributor.

I think that it would be useful to be able to have these individual links directly on the readme.

Is it possible to do so in some way?

**Comment by puf17640** [comment]
Hey there! Sorry for taking so long to reply I am currently very busy and to be honest, I forgot most of the stuff I did in this codebase, but the idea is really good and I have no clue how I didn't do it like that in the first place... 

It would be awesome if you could look into it, of course only if you feel like you are able to, if not, just tell me and I might scoop in a few minutes to have a closer look at it! 👍🏻

**Comment by stefanobartoletti** [comment]
Thank you for your reply, unfortunately at the moment I'm quite busy myself and I don't really have the chance to delve into this. 

Anyway this is just a "nice to have", not an essential feature, so feel free to address it only if you can, no problems on my part :)

**Comment by pujux** [comment]
In the rewrite, the contributors are now all linked with their github profiles.
