### ISSUE TITLE
Issue with Gist badge

### ISSUE THREAD

**Issue by Sarcares** [pujux/badge-it#41]
I tried to use the badge related to Gist for my profile (actually, I have no public Gists).
[Link](https://badges.pufler.dev/gists/Sarcares)

I retrieved this error: 
``
{
  "message": "An error occured while processing your request, please create an issue on https://github.com/puf17640/git-badges/issues and give as much detail as you can. Thanks!"
}
``

So I opened the issue. Is this issue triggered by the lack of public Gists on my profile? What do you think about that?

Thank you for your badges; they are really nice!

**Comment by katorly** [comment]
I've met this problem too. It seems that the gists' api will not respond when the requested user has no gists. This may lead to the problem of the badge.

**Comment by pujux** [comment]
This is fixed in the rewrite
