### ISSUE TITLE
An Idea For a Github Badge

### ISSUE THREAD

**Issue by CodingAce123** [pujux/badge-it#42]
Hi!
You Can Make a Badge on what Is The License Of The Repo
For Example- 
 (logo) License- MIT

**Comment by pujux** [comment]
this is already a badge offered by shields.io as you can see here:
[![GitHub license](https://img.shields.io/github/license/pujux/badge-it?color=brightgreen)](https://github.com/pujux/badge-it/blob/main/LICENSE)
