### ISSUE TITLE
Web server down

### ISSUE THREAD

**Issue by 0x11DFE** [pujux/badge-it#57]
title & look at my readme profile page.

**Comment by atrinh0** [comment]
https://github.com/puf17640/git-badges/issues/52#issuecomment-1175265604

**Comment by Mr-vabs** [comment]
@puf17640 hello sir, web server is down

**Comment by ademaro** [comment]
Hello! Steel down...

**Comment by pujux** [comment]
Will be up in a few days. Rewrite is done. Server is bought. Need to setup kubernetes and CI/CD for my projects again.

**Comment by pujux** [comment]
Took me a month to actually get this done because of time issues but just so you guys know, the API is up and running again and will be doing so for a long time now.
