### ISSUE TITLE
What IPs need to be whitelisted?

### ISSUE THREAD

**Issue by dtemir** [pujux/badge-it#59]
I noticed there was a line that wouldn't let me increase the visits counter because my PC IP wasn't whitelisted. 

Why do we need that line and does it mean we need to add something to our `.env` file to whitelist particular IPs?
https://github.com/puf17640/git-badges/blob/61755f30ef23c3841cf83ba227c1ebe72e913b3a/server.js#L46

Also, @puf17640 how much load did you experience when hosting by yourself? I could put it into one of my free Oracle microservices, but not sure if that's enough.

**Comment by puf17640** [comment]
good question, i haven't really touched the code in 2 years 😄  try taking it out when hosting it yourself and see. 

load was minimal as most of the stuff is cached anyway, try using your oracle microservice.
