### ISSUE TITLE
Is it possible to get private repos?

### ISSUE THREAD

**Issue by dimkagithub** [pujux/badge-it#74]
Hi!
Is it possible to get info from private repos?

**Comment by pujux** [comment]
what exactly do you mean?

**Comment by dimkagithub** [comment]
If the repository is private, then badge it does not have access to the repository, and therefore does not display information.
![Снимок экрана 2024-05-06 в 04 35 19](https://github.com/pujux/badge-it/assets/71010307/577ae9be-1bf8-4b31-9ad4-53a370029267)

**Comment by pujux** [comment]
yeah because I cannot access private repository information 😅 it's not possible, you would need to host it yourself with a PAT that can read your private repositories
